services:
  gateway:
    image: traefik:v3.6
    ports:
      - "80:80"
      - "9001:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  file-service:
    build: ./services/file-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-service.rule=Host(`localhost`) || Host(`77.42.41.153`)"
      - "traefik.http.routers.file-service.entrypoints=web"
      - "traefik.http.services.file-service.loadbalancer.server.port=8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=filesdb;Username=user;Password=pass

      - Minio__Endpoint=object-storage:9000
      - Minio__AccessKey=minioadmin
      - Minio__SecretKey=minioadmin

      - Jwt__Key=super_secret_key_must_be_very_long_at_least_32_chars_long_12345

    depends_on:
      - postgres
      - object-storage
  postgres:
    image: postgres:15
    container_name: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: filesdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  object-storage:
    image: minio/minio
    command: server /data --console-address ":9002"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - miniodata:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "9003:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: postgresql
    volumes:
      - pgadmin:/var/lib/pgadmin
  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

      #docker exec -it badfd5e1fa6c find / -name "kafka-topics*" 2>/dev/null
      #docker exec -it badfd5e1fa6c /opt/kafka/bin/kafka-topics.sh --create --topic test-topic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1
      #docker exec -it badfd5e1fa6c /opt/kafka/bin/kafka-console-producer.sh --topic test-topic --bootstrap-server localhost:9092
      #docker exec -it badfd5e1fa6c /opt/kafka/bin/kafka-console-consumer.sh --topic test-topic --from-beginning --bootstrap-server localhost:9092

volumes:
  pgdata:
  miniodata:
  pgadmin:
  kafka:
