services:
  gateway:
    image: traefik:v3.6
    ports:
      - "80:80"
      - "9001:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  file-service:
    build: ./services/file-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-service.rule=Host(`localhost`) || Host(`77.42.72.42`)"
      - "traefik.http.routers.file-service.entrypoints=web"
      - "traefik.http.services.file-service.loadbalancer.server.port=8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=filesdb;Username=user;Password=pass

    depends_on:
      - postgres
      - object-storage
  postgres:
    image: postgres:15
    container_name: yoko-postgres-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: filesdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  object-storage:
    image: minio/minio
    command: server /data --console-address ":9002"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - miniodata:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "9003:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: postgresql
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  miniodata:
  pgadmin:
